- name: Check if {{ project }} project exists
  uri:
    url: http://gerrit:8080/projects/{{ project }}
    status_code: 200, 404
  register: project_check

- name: Create {{ project }}
  when: project_check.status==404
  block:
    - name: Create temp dir for {{ project }} creation
      shell: mktemp -d
      register: project_tmp
    
    - name: Clone {{ project }} into temp dir
      when: clone_repo
      git:
        repo: 'https://github.com/matijapul/{{ project }}.git'
        dest: "{{ project_tmp.stdout }}"

    - name: Copy data into temp folder
      when: copy_src is defined
      copy:
        src: "{{ copy_src }}"
        dest: "{{ project_tmp.stdout }}"

    - name: Create {{ project }} project in Gerrit
      uri:
        url: http://gerrit:8080/a/projects/{{ project }}
        method: PUT
        user: admin
        password: secret
        status_code: 201

    - name: Create initial commit in {{ project }}
      shell:
        executable: /bin/sh
        chdir: "{{ project_tmp.stdout }}"
        cmd: |
          git init .
          git config user.name "Admin"
          git config user.email "admin@example.com"
          cat >.gitreview <<EOF
          [gerrit]
          host=localhost
          port=29418
          project={{ project }}
          EOF
          git add .
          git commit -m "Initial commit of {{ project }} to local gerrit"
          git remote add gerrit http://admin:secret@gerrit:8080/{{ project }}
          git push -f --set-upstream gerrit +HEAD:master
